[package]
name = "wasm2glulx-spectest-macro"
edition = "2021"
publish = false

[dependencies]
proc-macro2 = "1"
quote = "1"
syn = "2"
wasm2glulx = { path = "../wasm2glulx", features =["spectest"] }

[lib]
proc-macro = true
